'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { getSupabaseBrowserAsync } from '../../../../lib/supabase-browser';
import styles from '../list/listing.module.css';

const MIGRATION_SQL = `-- VoxelFlip Factory accounting ledger.
-- Service-role only: browser users must never be able to fabricate profit or costs.

create table if not exists public.voxelflip_profit_ledger (
  id bigint generated by default as identity primary key,
  wallet text not null check (wallet ~* '^0x[0-9a-f]{40}$'),
  contract_address text check (contract_address is null or contract_address ~* '^0x[0-9a-f]{40}$'),
  token_id text,
  session_id text,
  entry_type text not null check (entry_type in (
    'sale_gross','sale_fee','royalty_income','mint_gas','listing_gas',
    'generation_cost','mesh_cost','other_cost','adjustment'
  )),
  direction text not null check (direction in ('income','cost')),
  amount_eth numeric(38,18),
  amount_usd_cents bigint,
  source text not null,
  source_ref text not null unique,
  tx_hash text check (tx_hash is null or tx_hash ~* '^0x[0-9a-f]{64}$'),
  settlement_status text not null default 'pending' check (settlement_status in ('pending','estimated','verified')),
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (amount_eth is not null or amount_usd_cents is not null),
  check (amount_eth is null or amount_eth >= 0),
  check (amount_usd_cents is null or amount_usd_cents >= 0)
);

create index if not exists voxelflip_profit_ledger_wallet_time_idx
  on public.voxelflip_profit_ledger (lower(wallet), occurred_at desc);
create index if not exists voxelflip_profit_ledger_token_idx
  on public.voxelflip_profit_ledger (lower(contract_address), token_id);
create index if not exists voxelflip_profit_ledger_type_idx
  on public.voxelflip_profit_ledger (entry_type, settlement_status);

alter table public.voxelflip_profit_ledger enable row level security;
revoke all on table public.voxelflip_profit_ledger from anon, authenticated;
grant select, insert, update on table public.voxelflip_profit_ledger to service_role;
grant usage, select on sequence public.voxelflip_profit_ledger_id_seq to service_role;

comment on table public.voxelflip_profit_ledger is
  'Server-owned VoxelFlip income/cost ledger. A sale is gross proceeds until complete verified cost coverage exists; minting and unsold inventory never count as profit.';

-- Neural Core private server memory.
create table if not exists public.voxelflip_neural_memory (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('market_snapshot','recommendation','admin_config','trade_note')),
  wallet text,
  contract_address text,
  token_id text,
  confidence text,
  payload jsonb not null default '{}'::jsonb,
  observed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists voxelflip_neural_memory_wallet_time_idx
  on public.voxelflip_neural_memory (wallet, observed_at desc);
create index if not exists voxelflip_neural_memory_kind_time_idx
  on public.voxelflip_neural_memory (kind, observed_at desc);

alter table public.voxelflip_neural_memory enable row level security;
revoke all on table public.voxelflip_neural_memory from anon, authenticated;
grant select, insert, update, delete on table public.voxelflip_neural_memory to service_role;
grant usage, select on sequence public.voxelflip_neural_memory_id_seq to service_role;

comment on table public.voxelflip_neural_memory is
  'Server-only VoxelFlip Neural Core memory. Browser roles have no direct access; all reads and writes pass through authenticated admin routes.';
`;

function statusText(value) {
  return value ? 'READY' : 'WAITING';
}

export default function NeuralCoreSetupPage() {
  const [authState, setAuthState] = useState('loading');
  const [token, setToken] = useState('');
  const [status, setStatus] = useState(null);
  const [busy, setBusy] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');

  const check = useCallback(async accessToken => {
    if (!accessToken) return;
    setBusy(true);
    setError('');
    try {
      const response = await fetch('/api/admin/neural-core/setup', {
        cache: 'no-store',
        headers: { Authorization: `Bearer ${accessToken}` },
      });
      const data = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(data.error || 'Setup status could not be checked.');
      setStatus(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Setup status could not be checked.');
    } finally {
      setBusy(false);
    }
  }, []);

  useEffect(() => {
    let cancelled = false;
    let subscription;
    (async () => {
      try {
        const client = await getSupabaseBrowserAsync();
        const { data } = await client.auth.getSession();
        if (cancelled) return;
        const accessToken = data?.session?.access_token || '';
        if (!accessToken) {
          setAuthState('signed-out');
          return;
        }
        setToken(accessToken);
        setAuthState('ready');
        await check(accessToken);
        const result = client.auth.onAuthStateChange((_event, session) => {
          const next = session?.access_token || '';
          setToken(next);
          setAuthState(next ? 'ready' : 'signed-out');
        });
        subscription = result?.data?.subscription;
      } catch (err) {
        if (!cancelled) {
          setAuthState('signed-out');
          setError(err instanceof Error ? err.message : 'Google session could not be loaded.');
        }
      }
    })();
    return () => {
      cancelled = true;
      subscription?.unsubscribe?.();
    };
  }, [check]);

  async function copySql() {
    try {
      await navigator.clipboard.writeText(MIGRATION_SQL);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      setError('Your browser blocked clipboard access. Select the SQL below and copy it manually.');
    }
  }

  if (authState === 'loading') return <main className={styles.page}><section className={styles.locked}><h1>Checking Neural Core setup…</h1></section></main>;

  if (authState === 'signed-out') return <main className={styles.page}>
    <nav className={styles.nav}><Link href="/studio">VoxelPop</Link><em>NEURAL CORE SETUP · PRIVATE</em></nav>
    <section className={styles.locked}>
      <small>GOOGLE SESSION REQUIRED</small>
      <h1>Sign in to configure the backend.</h1>
      <p>The setup checker is protected by the same Neural Core admin allowlist.</p>
      <Link href="/studio#my-voxels">Open Studio and sign in →</Link>
    </section>
  </main>;

  const ledgerReady = Boolean(status?.database?.profitLedger?.ready);
  const memoryReady = Boolean(status?.database?.neuralMemory?.ready);

  return <main className={styles.page}>
    <nav className={styles.nav}><Link href="/admin/neural-core">← Neural Core</Link><em>BACKEND SETUP</em></nav>
    <header className={styles.hero}>
      <small>VERIFY → COPY → RUN ONCE → CHECK AGAIN</small>
      <h1>Turn on the<br/><em>real memory.</em></h1>
      <p>This activates the private profit ledger and Neural Core memory tables. The SQL grants browser users no direct access. It does not enable automatic signing or trading.</p>
    </header>

    <div className={styles.shell}>
      <section className={styles.panel}>
        <div className={styles.panelHead}><div><small>DATABASE</small><h2>{status?.ready ? 'Core storage is active.' : 'Two private tables.'}</h2></div><span className={styles.badge}>{status?.ready ? 'READY' : 'SETUP'}</span></div>
        <div className={styles.grid}>
          <article className={styles.metric}><small>PROFIT LEDGER · 011</small><b>{statusText(ledgerReady)}</b></article>
          <article className={styles.metric}><small>NEURAL MEMORY · 012</small><b>{statusText(memoryReady)}</b></article>
          <article className={styles.metric}><small>AUTO-SIGNING</small><b>OFF</b></article>
        </div>
        <div className={status?.ready ? styles.success : styles.notice} style={{marginTop:14}}>{status?.nextStep || 'Checking current database state…'}</div>
        {error && <div className={styles.error} style={{marginTop:14}}>{error}</div>}
      </section>

      {!status?.ready && <section className={styles.panel}>
        <div className={styles.panelHead}><div><small>ONE-TIME SQL</small><h2>Run migrations 011 + 012.</h2></div><span className={styles.badge}>NO SECRETS</span></div>
        <p style={{color:'#aaaab6',lineHeight:1.65}}>1. Tap <b>Copy SQL</b>. 2. Open your Voxel Vault project in Supabase. 3. Open <b>SQL Editor → New query</b>. 4. Paste and Run. 5. Return here and tap <b>Check again</b>.</p>
        <div className={styles.actions}>
          <button className={styles.primary} onClick={copySql}>{copied ? 'Copied ✓' : 'Copy SQL'}</button>
          <a className={styles.secondary} href="https://supabase.com/dashboard/projects" target="_blank" rel="noreferrer">Open Supabase ↗</a>
        </div>
        <div className={styles.field} style={{marginTop:16}}>
          <label>Exact SQL from migrations 011 + 012</label>
          <textarea readOnly value={MIGRATION_SQL} style={{width:'100%',minHeight:260,boxSizing:'border-box',background:'#0b0b10',color:'#b9bbc5',border:'1px solid #31313c',borderRadius:14,padding:14,fontFamily:'ui-monospace,SFMono-Regular,Menlo,monospace',fontSize:11,lineHeight:1.5}} />
        </div>
      </section>}

      <section className={styles.panel}>
        <div className={styles.panelHead}><div><small>SERVER READINESS</small><h2>Connected pieces</h2></div></div>
        <div className={styles.grid}>
          <article className={styles.metric}><small>OPENSEA</small><b>{statusText(Boolean(status?.services?.openSeaApiKey))}</b></article>
          <article className={styles.metric}><small>BASE RPC</small><b>{statusText(Boolean(status?.services?.productionRpc))}</b></article>
          <article className={styles.metric}><small>30M CRON</small><b>{statusText(Boolean(status?.services?.cronSecret))}</b></article>
        </div>
        <div className={styles.actions} style={{marginTop:16}}>
          <button className={styles.primary} onClick={() => check(token)} disabled={busy}>{busy ? 'Checking…' : 'Check again'}</button>
          {status?.ready ? <Link className={styles.secondary} href="/admin/neural-core">Open Neural Core →</Link> : <Link className={styles.secondary} href="/admin/neural-core/list">Listing Assistant →</Link>}
        </div>
      </section>
    </div>
  </main>;
}
