'use client';
import {useEffect,useState} from 'react';
import {getSupabaseBrowser} from '../../lib/supabase-browser';

export default function MyVoxels(){
 const [user,setUser]=useState<any>(null);const [assets,setAssets]=useState<any[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 async function load(){try{const supabase=getSupabaseBrowser();const {data:{session}}=await supabase.auth.getSession();setUser(session?.user||null);if(session?.user){const {data,error:e}=await supabase.from('voxelpop_assets').select('*').order('created_at',{ascending:false});if(e)throw e;setAssets(data||[]);}}catch(e:any){setError(e?.message||'Could not load your voxels.')}finally{setLoading(false)}}
 useEffect(()=>{load();let sub:any;try{sub=getSupabaseBrowser().auth.onAuthStateChange(()=>load()).data.subscription}catch{}return()=>sub?.unsubscribe?.()},[]);
 async function google(){try{const supabase=getSupabaseBrowser();await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${location.origin}/my-voxels`}})}catch(e:any){setError(e?.message||'Google sign-in is not available yet.')}}
 async function signOut(){await getSupabaseBrowser().auth.signOut();setUser(null);setAssets([])}
 return <main style={{minHeight:'100vh',background:'#fffaf0',color:'#2d1662',fontFamily:'system-ui,sans-serif',padding:'24px'}}><div style={{maxWidth:980,margin:'0 auto'}}><nav style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16}}><a href="/" style={{display:'flex',alignItems:'center',gap:10,color:'inherit',textDecoration:'none',fontWeight:900,fontSize:22}}><img src="/voxelpop/voxelpop-logo.png" alt="VoxelPop" width="46" height="46" style={{borderRadius:12}}/>VoxelPop</a>{user&&<button onClick={signOut} style={{border:'1px solid #ddd',background:'white',borderRadius:999,padding:'10px 16px'}}>Sign out</button>}</nav><section style={{padding:'72px 0 28px'}}><div style={{fontSize:13,fontWeight:900,letterSpacing:2,color:'#7040c9'}}>MY VOXELS</div><h1 style={{fontSize:'clamp(42px,8vw,76px)',lineHeight:.95,margin:'10px 0 18px'}}>Your voxel library.</h1><p style={{fontSize:18,maxWidth:620,color:'#6d6480'}}>Sign in to keep your VoxelPop creations connected to your account and find them again across devices.</p></section>{error&&<div style={{padding:16,borderRadius:14,background:'#fff0f0',marginBottom:20}}>{error}</div>}{loading?<p>Loading…</p>:!user?<div style={{background:'white',border:'1px solid #e8def7',borderRadius:24,padding:28,maxWidth:480,boxShadow:'0 16px 50px #32106e12'}}><h2 style={{fontSize:28,marginTop:0}}>Save your voxels</h2><p>Use your Google account for a quick, password-free VoxelPop login.</p><button onClick={google} style={{width:'100%',padding:'15px 18px',border:0,borderRadius:14,background:'#30127c',color:'white',fontWeight:900,fontSize:16}}>Continue with Google</button></div>:assets.length===0?<div style={{background:'white',border:'1px solid #e8def7',borderRadius:24,padding:28}}><h2>No saved voxels yet</h2><p>Your signed-in VoxelPop creations will appear here.</p><a href="/" style={{fontWeight:900,color:'#6d28d9'}}>Create a voxel →</a></div>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:18}}>{assets.map(a=><article key={a.id} style={{background:'white',border:'1px solid #e8def7',borderRadius:22,padding:14,overflow:'hidden'}}>{a.image_data&&<img src={a.image_data} alt={a.name} style={{width:'100%',aspectRatio:'1',objectFit:'contain',borderRadius:15,background:'#f6f2fb'}}/>}<h3 style={{fontSize:20,marginBottom:6}}>{String(a.name||'Your voxel').replaceAll('-',' ')}</h3><p style={{color:'#756d82',minHeight:42}}>{a.idea||'Custom VoxelPop asset'}</p><span style={{fontSize:12,fontWeight:900,color:'#6d28d9'}}>{a.mesh_status==='ready'?'3D READY':'SAVED VOXEL'}</span></article>)}</div>}</div></main>
}