'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { REAL_WORLD_CATALOG } from '../../lib/realWorldCatalog';
import RealWorld3DNFT from '../components/RealWorld3DNFT';
import '../components/CJMarketplace.css';

function modelState(item){const model=item.modelUri||item.digitalTwin?.modelUrl;if(model&&item.digitalTwin?.exactModelVerified)return'verified';if(model)return'review';return'pending'}
function isReady(item){return Boolean(item.fulfillmentReady&&item.purchaseAssetId&&modelState(item)==='verified')}

export default function MarketplacePage(){
 const[query,setQuery]=useState('');const[category,setCategory]=useState('all');const[selectedId,setSelectedId]=useState(REAL_WORLD_CATALOG[0]?.id||'');
 const categories=useMemo(()=>['all',...new Set(REAL_WORLD_CATALOG.map(item=>item.type))],[]);
 const products=useMemo(()=>REAL_WORLD_CATALOG.filter(item=>{const haystack=`${item.name} ${item.type} ${item.sourceName}`.toLowerCase();return(!query||haystack.includes(query.toLowerCase()))&&(category==='all'||item.type===category)}),[query,category]);
 const selected=REAL_WORLD_CATALOG.find(item=>item.id===selectedId)||products[0]||REAL_WORLD_CATALOG[0];
 const verified=REAL_WORLD_CATALOG.filter(item=>modelState(item)==='verified').length;
 return <main className="cj-page">
   <header className="cj-header"><Link className="cj-brand" href="/">VOXEL <b>VAULT</b></Link><nav className="cj-nav"><Link href="/">Home</Link><a href="#catalog">Find</a><Link href="/scan">Scan</Link><Link href="/vault">Vault</Link></nav><span className="cj-count">{REAL_WORLD_CATALOG.length} OBJECTS</span></header>
   <section className="cj-hero"><div><div className="cj-kicker">THE PHYSICAL / DIGITAL CATALOG</div><h1>Find something<br/><em>worth keeping.</em></h1><p>Every object begins as a real CJ-sourced product. Exact interactive 3D appears only after accuracy review. Until then, the product stays visible, honest, and locked from checkout.</p><div className="cj-trust"><span>{REAL_WORLD_CATALOG.length} mapped CJ products</span><span>{verified} verified 3D twins</span><span>USD checkout</span><span>No wallet required</span></div></div>{selected&&<div className="cj-feature"><div className="cj-featureTop"><small>SELECTED OBJECT</small><b>{modelState(selected)==='verified'?'VERIFIED TWIN':'ACCURACY PENDING'}</b></div><RealWorld3DNFT item={selected} hero/><div className="cj-featureFoot"><div><small>{selected.type}</small><strong>{selected.name}</strong></div><b>${selected.customerPriceUsd}</b></div></div>}</section>
   <section id="catalog" className="cj-catalog"><div className="cj-sectionTitle"><div><small>OBJECT INDEX</small><h2>Browse the vault.</h2></div><p>Tap any object to bring it into the large viewer.</p></div><div className="cj-toolbar"><input className="cj-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by object, category, supplier…"/><select className="cj-select" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(value=><option key={value} value={value}>{value==='all'?'All categories':value}</option>)}</select></div>
   {products.length?<div className="cj-grid">{products.map((item,index)=>{const state=modelState(item);const ready=isReady(item);const active=selected?.id===item.id;return <article className={`cj-card ${active?'is-active':''}`} key={item.id}><button className="cj-selectCard" onClick={()=>setSelectedId(item.id)} aria-label={`Preview ${item.name}`}><span>{String(index+1).padStart(2,'0')}</span><b>{active?'VIEWING':'PREVIEW'}</b></button><div className="cj-cardTop"><div><small>{item.type}</small><h2>{item.name}</h2></div><div className="cj-price"><strong>${item.customerPriceUsd}</strong><span>target bundle</span></div></div><div className="cj-media"><RealWorld3DNFT item={item}/></div><div className="cj-meta"><div className="cj-status"><span className="ok">CJ MAPPED</span><span>{state==='verified'?'3D VERIFIED':state==='review'?'3D REVIEW':'3D PENDING'}</span><span>{ready?'BUY READY':'LOCKED'}</span></div><div className="cj-source"><span>SKU · {item.supplierSku}</span><a href={item.sourceUrl} target="_blank" rel="noreferrer">CJ source ↗</a></div></div><div className="cj-actions">{ready?<Link className="cj-primary" href={`/marketplace?purchase=${encodeURIComponent(item.purchaseAssetId)}`}>Buy with card</Link>:<span className="cj-locked">Verification required</span>}<button className="cj-secondary" onClick={()=>{setSelectedId(item.id);window.scrollTo({top:0,behavior:'smooth'})}}>View large</button></div></article>})}</div>:<div className="cj-empty">No objects match that search.</div>}</section>
   <section className="cj-policy"><small>THE VOXEL RULE</small><h2>Catalog first. Accuracy before commerce.</h2><p>Voxel Vault can scale to hundreds of CJ products without pretending every product already has an exact 3D twin. Catalog visibility, 3D verification, fulfillment readiness, and checkout eligibility are separate states.</p><div className="cj-pipeline"><span>01 · CJ MAPPED</span><i>→</i><span>02 · MEDIA VERIFIED</span><i>→</i><span>03 · 3D VERIFIED</span><i>→</i><span>04 · CHECKOUT READY</span></div></section>
   <footer className="cj-footer"><span>VOXEL VAULT · REAL OBJECTS / DIGITAL TWINS</span><Link href="/">Home</Link><span>NO CRYPTO REQUIRED</span></footer>
 </main>
}
