'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { REAL_WORLD_CATALOG } from '../../lib/realWorldCatalog';
import RealWorld3DNFT from '../components/RealWorld3DNFT';
import '../components/CJMarketplace.css';

function modelState(item){const model=item.modelUri||item.digitalTwin?.modelUrl;if(model&&item.digitalTwin?.exactModelVerified)return'verified';if(model)return'review';return'pending'}
function isReady(item){return Boolean(item.fulfillmentReady&&item.purchaseAssetId&&modelState(item)==='verified')}
function selectUrl(id){return `/marketplace?object=${encodeURIComponent(id)}`}

export default function MarketplacePage(){
 const[query,setQuery]=useState('');const[category,setCategory]=useState('all');const[status,setStatus]=useState('all');const[selectedId,setSelectedId]=useState(REAL_WORLD_CATALOG[0]?.id||'');
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('object');if(id&&REAL_WORLD_CATALOG.some(item=>item.id===id))setSelectedId(id)},[]);
 const categories=useMemo(()=>['all',...new Set(REAL_WORLD_CATALOG.map(item=>item.type))],[]);
 const products=useMemo(()=>REAL_WORLD_CATALOG.filter(item=>{const haystack=`${item.name} ${item.type} ${item.sourceName} ${item.supplierSku}`.toLowerCase();const state=modelState(item);const statusMatch=status==='all'||(status==='ready'&&isReady(item))||(status==='verified'&&state==='verified')||(status==='pending'&&state!=='verified');return(!query||haystack.includes(query.toLowerCase()))&&(category==='all'||item.type===category)&&statusMatch}).sort((a,b)=>Number(isReady(b))-Number(isReady(a))||Number(modelState(b)==='verified')-Number(modelState(a)==='verified')),[query,category,status]);
 const selected=REAL_WORLD_CATALOG.find(item=>item.id===selectedId)||products[0]||REAL_WORLD_CATALOG[0];
 const verified=REAL_WORLD_CATALOG.filter(item=>modelState(item)==='verified').length;const ready=REAL_WORLD_CATALOG.filter(isReady).length;
 function choose(item,{top=false}={}){setSelectedId(item.id);window.history.replaceState(null,'',selectUrl(item.id));if(top)window.scrollTo({top:0,behavior:'smooth'})}
 return <main className="cj-page">
   <header className="cj-header"><Link className="cj-brand" href="/">VOXEL <b>VAULT</b></Link><nav className="cj-nav"><Link href="/">Home</Link><a href="#catalog">Find</a><Link href="/scan">Scan</Link><Link href="/vault">Vault</Link></nav><span className="cj-count">{REAL_WORLD_CATALOG.length} OBJECTS</span></header>
   <section className="cj-hero"><div><div className="cj-kicker">THE PHYSICAL / DIGITAL OBJECT INDEX</div><h1>Browse the real.<br/><em>Inspect the twin.</em></h1><p>Every object begins as a real CJ-sourced product. The catalog can grow quickly, but exact interactive 3D and checkout only unlock product by product after accuracy and fulfillment review.</p><div className="cj-trust"><span>{REAL_WORLD_CATALOG.length} CJ mapped</span><span>{verified} exact 3D verified</span><span>{ready} checkout ready</span><span>USD · no wallet to buy</span></div></div>{selected&&<div className="cj-feature"><div className="cj-featureTop"><small>SELECTED OBJECT · {selected.supplierSku}</small><b>{modelState(selected)==='verified'?'VERIFIED TWIN':modelState(selected)==='review'?'3D REVIEW':'ACCURACY PENDING'}</b></div><RealWorld3DNFT item={selected} hero/><div className="cj-featureFoot"><div><small>{selected.type}</small><strong>{selected.name}</strong><span>{isReady(selected)?'READY TO BUY':'PREVIEW ONLY · CHECKOUT LOCKED'}</span></div><b>${selected.customerPriceUsd}</b></div><div className="cj-featureActions">{isReady(selected)?<Link className="cj-primary" href={`/marketplace?purchase=${encodeURIComponent(selected.purchaseAssetId)}`}>Buy with card</Link>:<span className="cj-locked">Verification required before checkout</span>}<a className="cj-secondary" href={selected.sourceUrl} target="_blank" rel="noreferrer">Verify CJ source ↗</a></div></div>}</section>
   <section id="catalog" className="cj-catalog"><div className="cj-sectionTitle"><div><small>OBJECT INDEX</small><h2>Choose what enters the viewer.</h2></div><p>{products.length} shown · filter by readiness, category, supplier, or SKU.</p></div><div className="cj-toolbar"><input className="cj-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search object, category, supplier or SKU…"/><select className="cj-select" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(value=><option key={value} value={value}>{value==='all'?'All categories':value}</option>)}</select><select className="cj-select" value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filter by readiness"><option value="all">All readiness states</option><option value="ready">Checkout ready</option><option value="verified">3D verified</option><option value="pending">3D pending / review</option></select></div>
   {products.length?<div className="cj-grid">{products.map((item,index)=>{const state=modelState(item);const itemReady=isReady(item);const active=selected?.id===item.id;return <article className={`cj-card ${active?'is-active':''}`} key={item.id}><button className="cj-selectCard" onClick={()=>choose(item)} aria-label={`Preview ${item.name}`}><span>{String(index+1).padStart(2,'0')}</span><b>{active?'VIEWING':'SELECT'}</b></button><div className="cj-cardTop"><div><small>{item.type}</small><h2>{item.name}</h2></div><div className="cj-price"><strong>${item.customerPriceUsd}</strong><span>target bundle</span></div></div><div className="cj-media"><RealWorld3DNFT item={item}/></div><div className="cj-meta"><div className="cj-status"><span className="ok">CJ MAPPED</span><span>{state==='verified'?'3D VERIFIED':state==='review'?'3D REVIEW':'3D PENDING'}</span><span>{itemReady?'BUY READY':'LOCKED'}</span></div><div className="cj-source"><span>SKU · {item.supplierSku}</span><a href={item.sourceUrl} target="_blank" rel="noreferrer">CJ source ↗</a></div></div><div className="cj-actions">{itemReady?<Link className="cj-primary" href={`/marketplace?purchase=${encodeURIComponent(item.purchaseAssetId)}`}>Buy with card</Link>:<span className="cj-locked">Verification required</span>}<button className="cj-secondary" onClick={()=>choose(item,{top:true})}>Open large</button></div></article>})}</div>:<div className="cj-empty">No objects match those filters.</div>}</section>
   <section className="cj-policy"><small>THE VOXEL RULE</small><h2>Discovery can scale. Trust cannot be skipped.</h2><p>Catalog visibility, supplier mapping, exact 3D verification, fulfillment readiness, and checkout eligibility stay separate. That is how Voxel Vault can grow to hundreds of real products without turning pending media into a false promise.</p><div className="cj-pipeline"><span>01 · CJ MAPPED</span><i>→</i><span>02 · MEDIA VERIFIED</span><i>→</i><span>03 · 3D VERIFIED</span><i>→</i><span>04 · CHECKOUT READY</span></div></section>
   <footer className="cj-footer"><span>VOXEL VAULT · REAL OBJECTS / DIGITAL TWINS</span><Link href="/">Home</Link><span>NO CRYPTO REQUIRED</span></footer>
 </main>
}
