'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { REAL_WORLD_CATALOG } from '../../lib/realWorldCatalog';
import RealWorld3DNFT from '../components/RealWorld3DNFT';
import CJProductCard from '../components/CJProductCard';
import '../components/CJMarketplace.css';
import '../components/CJMarketplaceCards.css';
import '../components/ReadinessClarity.css';

function modelState(item){const model=item.modelUri||item.digitalTwin?.modelUrl;if(model&&item.digitalTwin?.exactModelVerified)return'verified';if(model)return'review';return'pending'}
function isReady(item){return Boolean(item.fulfillmentReady&&item.purchaseAssetId&&modelState(item)==='verified')}
function selectedState(item){const state=modelState(item);if(state==='verified')return'EXACT 3D APPROVED';if(state==='review')return'3D UNDER REVIEW';return'3D GENERATES ON OPEN'}
function selectUrl(id){return `/marketplace?object=${encodeURIComponent(id)}`}

export default function MarketplacePage(){
 const[query,setQuery]=useState('');const[category,setCategory]=useState('all');const[status,setStatus]=useState('all');const[selectedId,setSelectedId]=useState(REAL_WORLD_CATALOG[0]?.id||'');
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('object');if(id&&REAL_WORLD_CATALOG.some(item=>item.id===id))setSelectedId(id)},[]);
 const categories=useMemo(()=>['all',...new Set(REAL_WORLD_CATALOG.map(item=>item.type))],[]);
 const products=useMemo(()=>REAL_WORLD_CATALOG.filter(item=>{const haystack=`${item.name} ${item.type} ${item.sourceName} ${item.supplierSku}`.toLowerCase();const state=modelState(item);const statusMatch=status==='all'||(status==='ready'&&isReady(item))||(status==='verified'&&state==='verified')||(status==='pending'&&state!=='verified');return(!query||haystack.includes(query.toLowerCase()))&&(category==='all'||item.type===category)&&statusMatch}).sort((a,b)=>Number(isReady(b))-Number(isReady(a))||Number(modelState(b)==='verified')-Number(modelState(a)==='verified')),[query,category,status]);
 const selected=REAL_WORLD_CATALOG.find(item=>item.id===selectedId)||products[0]||REAL_WORLD_CATALOG[0];
 const verified=REAL_WORLD_CATALOG.filter(item=>modelState(item)==='verified').length;const ready=REAL_WORLD_CATALOG.filter(isReady).length;
 function choose(item,{top=false}={}){setSelectedId(item.id);window.history.replaceState(null,'',selectUrl(item.id));if(top)window.scrollTo({top:0,behavior:'smooth'})}
 return <main className="cj-page">
   <header className="cj-header"><Link className="cj-brand" href="/">VOXEL <b>VAULT</b></Link><nav className="cj-nav"><Link href="/">Home</Link><a href="#catalog">Find</a><Link href="/scan">Scan</Link><Link href="/vault">Vault</Link></nav><span className="cj-count">{REAL_WORLD_CATALOG.length} PRODUCTS</span></header>
   <section className="cj-hero"><div><div className="cj-kicker">REAL CJ PRODUCTS · 3D BUILDS AUTOMATICALLY</div><h1>Find the product.<br/><em>See it in 3D.</em></h1><p>Every listing maps to a real CJ product. Voxel Vault handles the syncing and readiness checks behind the scenes. You browse normally, pay in USD when a product is ready, and receive the physical product with its 3D collectible included.</p><div className="cj-trust"><span>{REAL_WORLD_CATALOG.length} CJ products synced</span><span>{verified} exact 3D approved</span><span>{ready} live checkout</span><span>USD · no wallet to buy</span></div><div className="cj-explainer"><b>You do not verify products.</b><span>“Approved” only means Voxel Vault has checked that the generated 3D matches the exact CJ item closely enough to sell as that product. Until then, you can still browse the real CJ listing and generate an interactive 3D preview.</span></div></div>{selected&&<div className="cj-feature"><div className="cj-featureTop"><small>SELECTED · {selected.supplierSku}</small><b>{selectedState(selected)}</b></div><RealWorld3DNFT item={selected} hero/><div className="cj-featureFoot"><div><small>{selected.type}</small><strong>{selected.name}</strong><span>{isReady(selected)?'READY TO BUY':'BROWSE + 3D PREVIEW · NOT FOR SALE YET'}</span></div><b>${selected.customerPriceUsd}</b></div><div className="cj-featureActions">{isReady(selected)?<Link className="cj-primary" href={`/marketplace?purchase=${encodeURIComponent(selected.purchaseAssetId)}`}>Buy with card</Link>:<span className="cj-locked">Checkout opens automatically when ready</span>}<a className="cj-secondary" href={selected.sourceUrl} target="_blank" rel="noreferrer">View CJ listing ↗</a></div></div>}</section>
   <section id="catalog" className="cj-catalog"><div className="cj-sectionTitle"><div><small>PRODUCT INDEX</small><h2>Pick anything. Open it in 3D.</h2></div><p>{products.length} shown · selecting a pending product starts its 3D review preview.</p></div><div className="cj-toolbar"><input className="cj-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search product, category or SKU…"/><select className="cj-select" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(value=><option key={value} value={value}>{value==='all'?'All categories':value}</option>)}</select><select className="cj-select" value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filter by readiness"><option value="all">All products</option><option value="ready">Ready to buy</option><option value="verified">Exact 3D approved</option><option value="pending">3D building / review</option></select></div>
   {products.length?<div className="cj-grid">{products.map((item,index)=>{const state=modelState(item);const itemReady=isReady(item);const active=selected?.id===item.id;return <CJProductCard key={item.id} item={item} index={index} active={active} state={state} ready={itemReady} onSelect={()=>choose(item)} onOpen={()=>choose(item,{top:true})}/>})}</div>:<div className="cj-empty">No products match those filters.</div>}</section>
   <section className="cj-policy"><small>HOW A PRODUCT BECOMES BUYABLE</small><h2>Automation first. Accuracy before checkout.</h2><p>You do not need to manually verify anything. Voxel Vault syncs the CJ product and supplier media, generates the 3D review asset, checks that the model represents the same physical item, confirms fulfillment readiness, and only then enables card checkout.</p><div className="cj-pipeline"><span>01 · CJ SYNCED</span><i>→</i><span>02 · 3D GENERATED</span><i>→</i><span>03 · EXACT 3D APPROVED</span><i>→</i><span>04 · FULFILLMENT READY</span><i>→</i><span>05 · BUY WITH CARD</span></div></section>
   <footer className="cj-footer"><span>VOXEL VAULT · REAL PRODUCTS / 3D COLLECTIBLES</span><Link href="/">Home</Link><span>NO CRYPTO REQUIRED</span></footer>
 </main>
}
