import { NextResponse } from 'next/server';
import { stripe } from '../../../../lib/stripe-server';

export const runtime = 'nodejs';

const names=['sword','shield','red-potion','blue-potion','coin','gem','treasure-chest','key','heart','star','tree','rock','crystal','torch','helmet','boot','pickaxe','axe','hammer','bow','arrow','scroll','book','map','backpack','crown','ring','magic-orb','portal','castle','tower','house','crate','barrel','mushroom','slime'];

function svg(name:string,i:number){const h=(i*37)%360,h2=(h+35)%360,h3=(h+70)%360;return `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512"><rect width="512" height="512" fill="none"/><g transform="translate(256 236)"><polygon points="0,-128 138,-58 0,14 -138,-58" fill="hsl(${h} 82% 62%)"/><polygon points="-138,-58 0,14 0,164 -138,92" fill="hsl(${h2} 72% 44%)"/><polygon points="138,-58 0,14 0,164 138,92" fill="hsl(${h3} 70% 34%)"/><polygon points="0,-80 34,-46 0,-10 -34,-46" fill="white" fill-opacity=".88"/><rect x="-8" y="-4" width="16" height="70" rx="4" fill="white" fill-opacity=".72"/><rect x="-42" y="20" width="84" height="16" rx="4" fill="white" fill-opacity=".72"/></g><text x="256" y="458" text-anchor="middle" font-family="Arial,sans-serif" font-size="28" font-weight="700" fill="#111">${name.replaceAll('-',' ').toUpperCase()}</text></svg>`}

function crc32(buf:Buffer){let c=0xffffffff;for(const b of buf){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0}
function zip(files:{name:string,data:string}[]){const locals:Buffer[]=[];const centrals:Buffer[]=[];let offset=0;for(const f of files){const n=Buffer.from(f.name),d=Buffer.from(f.data),crc=crc32(d);const l=Buffer.alloc(30);l.writeUInt32LE(0x04034b50,0);l.writeUInt16LE(20,4);l.writeUInt16LE(0,6);l.writeUInt16LE(0,8);l.writeUInt32LE(crc,14);l.writeUInt32LE(d.length,18);l.writeUInt32LE(d.length,22);l.writeUInt16LE(n.length,26);locals.push(l,n,d);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50,0);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt32LE(crc,16);c.writeUInt32LE(d.length,20);c.writeUInt32LE(d.length,24);c.writeUInt16LE(n.length,28);c.writeUInt32LE(offset,42);centrals.push(c,n);offset+=l.length+n.length+d.length}const central=Buffer.concat(centrals),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(central.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,central,end])}

export async function GET(request:Request){try{const id=new URL(request.url).searchParams.get('session_id');if(!id)return NextResponse.json({error:'Missing checkout session.'},{status:400});const session=await stripe.checkout.sessions.retrieve(id);if(session.payment_status!=='paid'||session.metadata?.product!=='voxel-creator-pack-v1')return NextResponse.json({error:'A completed purchase is required.'},{status:403});const license=`VOXEL CREATOR PACK COMMERCIAL LICENSE\n\nYou may use and modify these assets in personal and commercial finished products, games, videos, social media, marketing and client work.\n\nYou may not resell, redistribute, sublicense or give away the source files as a competing asset pack. No trademark rights or financial results are promised.`;const ads=`FACEBOOK AD STARTERS\n\n1. Stop building every icon from scratch. Get 36 editable voxel assets for games, thumbnails and creator projects. $15. Instant download.\n\n2. 36 editable voxel assets for less than one custom icon. SVG files + commercial-use rights. Get the pack for $15.\n\n3. Need game art today? Weapons, loot, props, buildings, magic items and more. 36 assets. $15. Instant access.`;const files=names.map((n,i)=>({name:`assets/${String(i+1).padStart(2,'0')}-${n}.svg`,data:svg(n,i)}));files.push({name:'LICENSE.txt',data:license},{name:'FACEBOOK-AD-COPY.txt',data:ads},{name:'README.txt',data:'VOXEL CREATOR PACK — 36 editable SVG assets. Import into Figma, Illustrator, Canva, Photopea, browsers, game pipelines, or any SVG-compatible editor.'});const body=zip(files);return new Response(body,{headers:{'Content-Type':'application/zip','Content-Disposition':'attachment; filename="voxel-creator-pack-36.zip"','Cache-Control':'private, no-store'}})}catch(e){console.error('creator pack download failed',e);return NextResponse.json({error:'Unable to verify purchase.'},{status:500})}}