'use client';
import {useEffect,useRef,useState} from 'react';
import type {ChangeEvent} from 'react';
import GeneratedMeshViewer from './GeneratedMeshViewer';
import VoxelFlipPanel from './VoxelFlipPanel';
import styles from './success.module.css';

type Brief={idea:string;style:string;reference:string;referenceName?:string};
type Asset={name:string;dataUrl:string};
type Mesh={status:'idle'|'starting'|'building'|'ready'|'error';progress:number;taskId:string;modelUrl:string;error:string};
const defaultBrief:Brief={idea:'Cozy medieval fantasy adventurer with warm lantern light, mossy armor and emerald accents',style:'polished',reference:''};
const emptyMesh=():Mesh=>({status:'idle',progress:0,taskId:'',modelUrl:'',error:''});
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function compressReference(file:File){const bitmap=await createImageBitmap(file);const max=640,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Image preview is not supported in this browser.');ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();return canvas.toDataURL('image/jpeg',.78);}

export default function PackBuilder({sessionId}:{sessionId:string}){
 const mounted=useRef(true);const recoveringTask=useRef(false);const [brief,setBrief]=useState<Brief>(defaultBrief);const [status,setStatus]=useState<'ready'|'generating'|'done'|'error'>('ready');const [message,setMessage]=useState('');const [asset,setAsset]=useState<Asset|null>(null);const [mesh,setMesh]=useState<Mesh>(emptyMesh());const [generationsLeft,setGenerationsLeft]=useState(2);
 const storageKey=`voxelpop:${sessionId}`;
 useEffect(()=>{mounted.current=true;try{const stored=sessionStorage.getItem('voxelPackBrief');if(stored)setBrief({...defaultBrief,...JSON.parse(stored)});const saved=localStorage.getItem(storageKey);if(saved){const parsed=JSON.parse(saved);if(parsed?.asset?.dataUrl){setAsset(parsed.asset);setMesh(parsed.mesh||emptyMesh());if(Number.isFinite(parsed.generationsLeft))setGenerationsLeft(parsed.generationsLeft);setStatus('done');setMessage('Your paid voxel was restored.')}}}catch{}return()=>{mounted.current=false}},[storageKey]);
 useEffect(()=>{if(!asset)return;try{localStorage.setItem(storageKey,JSON.stringify({asset,mesh,generationsLeft}))}catch{}},[asset,mesh,generationsLeft,storageKey]);
 useEffect(()=>{if(!sessionId||!asset||mesh.status!=='ready'||mesh.taskId||recoveringTask.current)return;recoveringTask.current=true;(async()=>{try{const response=await fetch('/api/creator-pack/mesh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId,index:0,image:asset.dataUrl,name:asset.name,idea:brief.idea,forceRestart:false})});const data=await response.json();if(response.ok&&data.taskId){setMesh(v=>({...v,taskId:String(data.taskId)}));setMessage('3D restored. VoxelFlip is ready below.');}}catch{}finally{recoveringTask.current=false}})()},[sessionId,asset,mesh.status,mesh.taskId,brief.idea]);
 async function chooseReference(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;try{setMessage('');setBrief(v=>({...v,referenceName:file.name,reference:''}));const data=await compressReference(file);setBrief(v=>({...v,reference:data,referenceName:file.name}));}catch(err){setMessage(err instanceof Error?err.message:'Could not read that image.')}}
 async function generate(improve=false){if(!sessionId){setStatus('error');setMessage('Checkout session missing. Return to VoxelPop and purchase the asset again.');return}if(brief.idea.trim().length<8){setStatus('error');setMessage('Add a short description of what you want.');return}if(improve&&!asset)return;setStatus('generating');setMessage(improve?'Improving your voxel…':'Creating your voxel…');try{const response=await fetch('/api/creator-pack/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId,idea:brief.idea.trim(),style:brief.style,reference:improve?asset?.dataUrl:brief.reference,improve})});const data=await response.json();if(!response.ok||!Array.isArray(data.images)||data.images.length!==1)throw new Error(data.error||'Generation failed.');const nextAsset={name:data.names?.[0]||'your-voxel',dataUrl:data.images[0]};setAsset(nextAsset);setMesh(emptyMesh());setGenerationsLeft(Math.max(0,Number(data.generationsLeft||0)));setStatus('done');setMessage(improve?'Improved. Build it when you love it.':'Ready. Improve it or build it in 3D.');}catch(err){setStatus(asset?'done':'error');setMessage(err instanceof Error?err.message:'Generation failed.')}}
 async function pollMesh(taskId:string){for(let i=0;i<180;i++){if(!mounted.current)return;const q=new URLSearchParams({sessionId,taskId});const response=await fetch(`/api/creator-pack/mesh?${q}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not read mesh status.');const s=String(data.status||'').toUpperCase();if(s==='SUCCEEDED'&&data.modelUrl){setMesh(v=>({...v,status:'ready',progress:100,modelUrl:data.modelUrl,error:''}));return}if(['FAILED','EXPIRED','CANCELED','CANCELLED'].includes(s))throw new Error(data.error||'The 3D provider could not complete this mesh.');setMesh(v=>({...v,status:'building',progress:Math.max(1,Math.min(99,Number(data.progress||0)))}));await wait(4000)}throw new Error('The mesh is taking longer than expected. Retry the status check shortly.');}
 async function buildMesh(){if(!asset)return;setMesh({...emptyMesh(),status:'starting',progress:1});try{const response=await fetch('/api/creator-pack/mesh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId,index:0,image:asset.dataUrl,name:asset.name,idea:brief.idea,forceRestart:mesh.status==='error'})});const data=await response.json();if(!response.ok||!data.taskId)throw new Error(data.error||'Could not start the 3D mesh.');setMesh(v=>({...v,status:'building',progress:2,taskId:data.taskId}));await pollMesh(data.taskId);}catch(err){setMesh(v=>({...v,status:'error',error:err instanceof Error?err.message:'3D mesh generation failed.'}))}}
 async function shareVoxel(){const shareUrl='https://www.voxelvault.io/?utm_source=customer_share&utm_medium=referral&utm_campaign=voxelpop_share&utm_content=finished_asset';const shareData={title:'VoxelPop',text:'I made a 3D voxel with VoxelPop. Try making yours for $1.99.',url:shareUrl};try{if(navigator.share){await navigator.share(shareData);setMessage('Shared.');return}if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(shareUrl);setMessage('Share link copied.');return}window.prompt('Copy this link to share VoxelPop:',shareUrl)}catch(err){if(err instanceof DOMException&&err.name==='AbortError')return;try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(shareUrl);setMessage('Share link copied.');return}}catch{}window.prompt('Copy this link to share VoxelPop:',shareUrl)}}
 function jumpToVoxelFlip(){document.getElementById('voxelflip-mint')?.scrollIntoView({behavior:'smooth',block:'start'});}
 const downloadQuery=mesh.taskId?new URLSearchParams({sessionId,taskId:mesh.taskId,download:'1'}).toString():'';const previewQuery=mesh.taskId?new URLSearchParams({sessionId,taskId:mesh.taskId,preview:'1'}).toString():'';const previewUrl=previewQuery?`/api/creator-pack/mesh?${previewQuery}`:'';
 return <main className={styles.page}><nav className={styles.nav}><a href="/"><img src="/voxelpop/voxelpop-logo.png" alt="VoxelPop"/><b>VoxelPop</b></a><em>PAID</em></nav><section className={styles.shell}>
  <div className={styles.header}><p>{status==='done'?'YOUR VOXEL':'ONE MORE TAP'}</p><h1>{status==='done'?'Love it?':'Create.'}</h1><span>{status==='done'?'Improve it, build it, then mint it if you want.':'Your payment is complete. Make your voxel now.'}</span></div>
  {status!=='done'&&<div className={styles.builder}><label><b>IDEA</b><textarea maxLength={600} value={brief.idea} onChange={e=>setBrief(v=>({...v,idea:e.target.value}))}/></label><div className={styles.styles}><b>STYLE</b><div>{[['polished','POLISHED'],['chunky','CHUNKY'],['cute','CUTE'],['dark','DARK']].map(([value,label])=><button type="button" key={value} className={brief.style===value?styles.active:''} onClick={()=>setBrief(v=>({...v,style:value}))}>{label}</button>)}</div></div><label className={styles.upload}><input type="file" accept="image/png,image/jpeg,image/webp" onChange={chooseReference}/>{brief.reference?<img src={brief.reference} alt="Reference preview"/>:<span>＋</span>}<div><b>PHOTO</b><small>{brief.referenceName||'optional reference'}</small></div></label><button className={styles.generate} aria-label="Create my paid voxel" disabled={status==='generating'} onClick={()=>generate(false)}>{status==='generating'?'CREATING…':'CREATE'}</button><small className={styles.note}>Includes up to 2 improvement passes.</small></div>}
  {message&&<div className={`${styles.message} ${status==='error'?styles.messageError:''}`}>{status==='generating'&&<i/>}{message}</div>}
  {status==='done'&&asset&&<><div className={styles.assetHeader}><div><p>PICK → BUILD → MINT</p><h2>Your voxel</h2></div><span>One big action at a time.</span></div><div className={styles.meshGrid}><article className={styles.meshCard}><div className={styles.meshCardTop}><b>01</b><span>{asset.name.replaceAll('-',' ')}</span></div>{mesh.status==='ready'&&previewUrl?<GeneratedMeshViewer url={previewUrl} label={asset.name}/>:<div className={styles.sourceImage}><img src={asset.dataUrl} alt="Your generated voxel"/>{['starting','building'].includes(mesh.status)&&<div className={styles.meshProgress}><i style={{width:`${Math.max(4,mesh.progress)}%`}}/><b>{mesh.status==='starting'?'STARTING':`BUILDING · ${mesh.progress}%`}</b></div>}</div>}<div className={styles.meshActions}>{mesh.status==='idle'&&<>{generationsLeft>0&&<><button className={styles.improveButton} aria-label={`Improve this voxel. ${generationsLeft} tries left`} onClick={()=>generate(true)}>IMPROVE</button><small className={styles.actionHint}>{generationsLeft} {generationsLeft===1?'try':'tries'} left</small></>}<button aria-label="Build this voxel in 3D" onClick={buildMesh}>BUILD</button></>}{['starting','building'].includes(mesh.status)&&<button disabled>BUILDING…</button>}{mesh.status==='error'&&<><p>{mesh.error}</p><button onClick={buildMesh}>RETRY</button></>}{mesh.status==='ready'&&<><a aria-label="Download GLB" href={`/api/creator-pack/mesh?${downloadQuery}`}>GLB</a><a className={styles.secondaryDownload} aria-label="Download image" href={asset.dataUrl} download={`${asset.name}.png`}>IMAGE</a><button className={styles.secondaryDownload} onClick={shareVoxel}>SHARE</button>{mesh.taskId?<button className={styles.mintButton} aria-label="Continue to VoxelFlip minting" onClick={jumpToVoxelFlip}>NEXT</button>:<button disabled>RESTORING…</button>}</>}</div></article></div>{mesh.status==='ready'&&mesh.taskId&&<VoxelFlipPanel sessionId={sessionId} taskId={mesh.taskId} image={asset.dataUrl} name={asset.name} idea={brief.idea}/>}</>}
  <footer><a href="/">BACK</a><span>AI output can vary. Inspect before production use.</span></footer></section></main>;
}
