'use client';
import {useEffect,useRef,useState} from 'react';
import type {ChangeEvent} from 'react';
import GeneratedMeshViewer from './GeneratedMeshViewer';
import styles from './success.module.css';

type Brief={idea:string;style:string;reference:string;referenceName?:string};
type Asset={name:string;dataUrl:string};
type Mesh={status:'idle'|'starting'|'building'|'ready'|'error';progress:number;taskId:string;modelUrl:string;error:string};
const defaultBrief:Brief={idea:'Cozy medieval fantasy adventurer with warm lantern light, mossy armor and emerald accents',style:'polished',reference:''};
const emptyMesh=():Mesh=>({status:'idle',progress:0,taskId:'',modelUrl:'',error:''});
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));

async function compressReference(file:File){const bitmap=await createImageBitmap(file);const max=640,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Image preview is not supported in this browser.');ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();return canvas.toDataURL('image/jpeg',.78);}

export default function PackBuilder({sessionId}:{sessionId:string}){
 const mounted=useRef(true);const [brief,setBrief]=useState<Brief>(defaultBrief);const [status,setStatus]=useState<'ready'|'generating'|'done'|'error'>('ready');const [message,setMessage]=useState('');const [asset,setAsset]=useState<Asset|null>(null);const [mesh,setMesh]=useState<Mesh>(emptyMesh());
 const storageKey=`voxelpop:${sessionId}`;
 useEffect(()=>{mounted.current=true;try{const stored=sessionStorage.getItem('voxelPackBrief');if(stored)setBrief({...defaultBrief,...JSON.parse(stored)});const saved=localStorage.getItem(storageKey);if(saved){const parsed=JSON.parse(saved);if(parsed?.asset?.dataUrl){setAsset(parsed.asset);setMesh(parsed.mesh||emptyMesh());setStatus('done');setMessage('Your paid voxel was restored. You can continue building or downloading it.')}}}catch{}return()=>{mounted.current=false}},[storageKey]);
 useEffect(()=>{if(!asset)return;try{localStorage.setItem(storageKey,JSON.stringify({asset,mesh}))}catch{}},[asset,mesh,storageKey]);
 async function chooseReference(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;try{setMessage('');setBrief(v=>({...v,referenceName:file.name,reference:''}));const data=await compressReference(file);setBrief(v=>({...v,reference:data,referenceName:file.name}));}catch(err){setMessage(err instanceof Error?err.message:'Could not read that image.')}}
 async function generate(){if(!sessionId){setStatus('error');setMessage('Checkout session missing. Return to VoxelPop and purchase the asset again.');return}if(brief.idea.trim().length<8){setStatus('error');setMessage('Add a short description of what you want.');return}setStatus('generating');setMessage('Creating your paid voxel image…');try{const response=await fetch('/api/creator-pack/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId,idea:brief.idea.trim(),style:brief.style})});const data=await response.json();if(!response.ok||!Array.isArray(data.images)||data.images.length!==1)throw new Error(data.error||'Generation failed.');const nextAsset={name:data.names?.[0]||'your-voxel',dataUrl:data.images[0]};setAsset(nextAsset);setMesh(emptyMesh());setStatus('done');setMessage('Your voxel is ready. Build the 3D mesh to rotate, move and download it.');}catch(err){setStatus('error');setMessage(err instanceof Error?err.message:'Generation failed.')}}
 async function pollMesh(taskId:string){for(let i=0;i<180;i++){if(!mounted.current)return;const q=new URLSearchParams({sessionId,taskId});const response=await fetch(`/api/creator-pack/mesh?${q}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not read mesh status.');const s=String(data.status||'').toUpperCase();if(s==='SUCCEEDED'&&data.modelUrl){setMesh(v=>({...v,status:'ready',progress:100,modelUrl:data.modelUrl,error:''}));return}if(['FAILED','EXPIRED','CANCELED','CANCELLED'].includes(s))throw new Error(data.error||'The 3D provider could not complete this mesh.');setMesh(v=>({...v,status:'building',progress:Math.max(1,Math.min(99,Number(data.progress||0)))}));await wait(4000)}throw new Error('The mesh is taking longer than expected. Retry the status check shortly.');}
 async function buildMesh(){if(!asset)return;setMesh({...emptyMesh(),status:'starting',progress:1});try{const response=await fetch('/api/creator-pack/mesh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId,index:0,image:asset.dataUrl,name:asset.name,idea:brief.idea,forceRestart:mesh.status==='error'})});const data=await response.json();if(!response.ok||!data.taskId)throw new Error(data.error||'Could not start the 3D mesh.');setMesh(v=>({...v,status:'building',progress:2,taskId:data.taskId}));await pollMesh(data.taskId);}catch(err){setMesh(v=>({...v,status:'error',error:err instanceof Error?err.message:'3D mesh generation failed.'}))}}
 const downloadQuery=mesh.taskId?new URLSearchParams({sessionId,taskId:mesh.taskId,download:'1'}).toString():'';
 const previewQuery=mesh.taskId?new URLSearchParams({sessionId,taskId:mesh.taskId,preview:'1'}).toString():'';
 const previewUrl=previewQuery?`/api/creator-pack/mesh?${previewQuery}`:'';
 return <main className={styles.page}>
  <nav className={styles.nav}><a href="/"><img src="/voxelpop/voxelpop-logo.png" alt="VoxelPop" style={{width:44,height:44,borderRadius:12}}/><b>VoxelPop</b></a><em>PAYMENT COMPLETE</em></nav>
  <section className={styles.shell}>
   <div className={styles.header}><p>YOUR VOXELPOP ASSET</p><h1>{status==='done'?'Make it move.':'Now make it yours.'}</h1><span>{status==='done'?'Turn your generated voxel into one real 3D mesh, then rotate and download it.':'Confirm the direction below. Your $1.99 purchase creates one custom voxel asset.'}</span></div>
   {status!=='done'&&<div className={styles.builder}>
    <label><b>Describe the person, character, product, pet or object</b><textarea maxLength={600} value={brief.idea} onChange={e=>setBrief(v=>({...v,idea:e.target.value}))}/></label>
    <div className={styles.styles}><b>Finish</b><div>{[['polished','Polished'],['chunky','Chunky'],['cute','Cute'],['dark','Dark fantasy']].map(([value,label])=><button type="button" key={value} className={brief.style===value?styles.active:''} onClick={()=>setBrief(v=>({...v,style:value}))}>{label}</button>)}</div></div>
    <label className={styles.upload}><input type="file" accept="image/png,image/jpeg,image/webp" onChange={chooseReference}/>{brief.reference?<img src={brief.reference} alt="Reference preview"/>:<span>＋</span>}<div><b>{brief.referenceName||'Optional reference image'}</b><small>{brief.reference?'Reference saved for this design':'Add a photo to help you plan the design; text drives the current generator'}</small></div></label>
    <button className={styles.generate} disabled={status==='generating'} onClick={generate}>{status==='generating'?'Generating your voxel…':'Generate my voxel'}</button><small className={styles.note}>One payment creates one voxel. Generation may take a few minutes; keep this tab open.</small>
   </div>}
   {message&&<div className={`${styles.message} ${status==='error'?styles.messageError:''}`}>{status==='generating'&&<i/>}{message}</div>}
   {status==='done'&&asset&&<><div className={styles.assetHeader}><div><p>GENERATE → MESH → MOVE</p><h2>Your voxel</h2></div><span>Build the mesh once, inspect it in 3D, then download your GLB.</span></div><div className={styles.meshGrid}><article className={styles.meshCard}><div className={styles.meshCardTop}><b>01</b><span>{asset.name.replaceAll('-',' ')}</span></div>{mesh.status==='ready'&&previewUrl?<GeneratedMeshViewer url={previewUrl} label={asset.name}/>:<div className={styles.sourceImage}><img src={asset.dataUrl} alt="Your generated voxel"/>{['starting','building'].includes(mesh.status)&&<div className={styles.meshProgress}><i style={{width:`${Math.max(4,mesh.progress)}%`}}/><b>{mesh.status==='starting'?'Starting 3D build':`Building mesh · ${mesh.progress}%`}</b></div>}</div>}<div className={styles.meshActions}>{mesh.status==='idle'&&<button onClick={buildMesh}>Build 3D Mesh</button>}{['starting','building'].includes(mesh.status)&&<button disabled>Building 3D Mesh…</button>}{mesh.status==='error'&&<><p>{mesh.error}</p><button onClick={buildMesh}>Retry 3D Mesh</button></>}{mesh.status==='ready'&&<><a href={`/api/creator-pack/mesh?${downloadQuery}`}>Download GLB</a><a className={styles.secondaryDownload} href={asset.dataUrl} download={`${asset.name}.png`}>Download image</a></>}</div></article></div></>}
   <footer><a href="/">← Back to VoxelPop</a><span>AI-generated output can vary. Inspect your asset before production use.</span></footer>
  </section>
 </main>;
}