'use client';
import {useEffect,useRef,useState} from 'react';
import type {ChangeEvent} from 'react';
import GeneratedMeshViewer from './GeneratedMeshViewer';
import styles from './success.module.css';
import {getSupabaseBrowserAsync} from '../../../lib/supabase-browser';
import {loadAccountVoxel,saveVoxelToAccount} from '../../../lib/voxelpop-account';

type Brief={idea:string;style:string;reference:string;referenceName?:string};
type Asset={name:string;dataUrl:string};
type Mesh={status:'idle'|'starting'|'building'|'ready'|'error';progress:number;taskId:string;modelUrl:string;error:string};
type Mint={tokenId?:string|number;owner?:string;hash?:string;txHash?:string;metadataUrl?:string;openSeaUrl?:string;explorerUrl?:string};
const defaultBrief:Brief={idea:'Cozy medieval fantasy adventurer with warm lantern light, mossy armor and emerald accents',style:'polished',reference:''};
const emptyMesh=():Mesh=>({status:'idle',progress:0,taskId:'',modelUrl:'',error:''});
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function compressReference(file:File){const bitmap=await createImageBitmap(file);const max=640,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Image preview is not supported in this browser.');ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();return canvas.toDataURL('image/jpeg',.78);}
async function prepareMeshImage(dataUrl:string){
 if(/^data:image\/(png|jpeg);base64,/.test(dataUrl)&&dataUrl.length<=2_400_000)return dataUrl;
 return new Promise<string>((resolve,reject)=>{
  const image=new Image();
  image.onload=()=>{
   const max=1024,scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight));
   const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));
   const ctx=canvas.getContext('2d');if(!ctx){reject(new Error('This browser could not prepare the generated image for 3D.'));return;}
   ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);
   let quality=.86,encoded=canvas.toDataURL('image/jpeg',quality);while(encoded.length>2_400_000&&quality>.5){quality-=.08;encoded=canvas.toDataURL('image/jpeg',quality)}
   if(encoded.length>3_500_000){reject(new Error('The generated image is still too large for the 3D builder. Try Improve this voxel once, then build again.'));return;}resolve(encoded);
  };
  image.onerror=()=>reject(new Error('The generated image could not be loaded for the 3D builder. Regenerate or improve this voxel and try again.'));
  image.src=dataUrl;
 });
}

export default function PackBuilder({sessionId}:{sessionId:string}){
 const mounted=useRef(true);const accountClient=useRef<any>(null);const [brief,setBrief]=useState<Brief>(defaultBrief);const [status,setStatus]=useState<'ready'|'generating'|'done'|'error'>('ready');const [message,setMessage]=useState('');const [asset,setAsset]=useState<Asset|null>(null);const [mesh,setMesh]=useState<Mesh>(emptyMesh());const [minted,setMinted]=useState<Mint|null>(null);const [generationsLeft,setGenerationsLeft]=useState(2);const [accountUser,setAccountUser]=useState<any>(null);const [accountMessage,setAccountMessage]=useState('');
 const storageKey=`voxelpop:${sessionId}`;
 useEffect(()=>{mounted.current=true;try{const stored=sessionStorage.getItem('voxelPackBrief');if(stored)setBrief({...defaultBrief,...JSON.parse(stored)});const saved=localStorage.getItem(storageKey);let restoredMint:Mint|null=null;if(saved){const parsed=JSON.parse(saved);if(parsed?.asset?.dataUrl){setAsset(parsed.asset);setMesh(parsed.mesh||emptyMesh());if(parsed.mint?.tokenId)restoredMint=parsed.mint;if(parsed.idea)setBrief(v=>({...v,idea:String(parsed.idea)}));if(Number.isFinite(parsed.generationsLeft))setGenerationsLeft(parsed.generationsLeft);setStatus('done');setMessage('Your paid voxel was restored. You can continue improving it or open its finished 3D version.')}}if(!restoredMint){const confirmed=JSON.parse(localStorage.getItem(`voxelflip:mint:${sessionId}`)||'null');if(confirmed?.tokenId)restoredMint=confirmed}if(restoredMint?.tokenId)setMinted(restoredMint)}catch{}return()=>{mounted.current=false}},[storageKey,sessionId]);
 useEffect(()=>{if(!asset)return;try{localStorage.setItem(storageKey,JSON.stringify({asset,mesh,mint:minted||undefined,generationsLeft,idea:brief.idea,updatedAt:new Date().toISOString()}))}catch{}},[asset,mesh,minted,generationsLeft,brief.idea,storageKey]);
 useEffect(()=>{const refreshMint=()=>{try{const confirmed=JSON.parse(localStorage.getItem(`voxelflip:mint:${sessionId}`)||'null');if(confirmed?.tokenId)setMinted(confirmed)}catch{}};window.addEventListener('focus',refreshMint);window.addEventListener('storage',refreshMint);return()=>{window.removeEventListener('focus',refreshMint);window.removeEventListener('storage',refreshMint)}},[sessionId]);
 useEffect(()=>{
  let active=true;let subscription:any=null;
  async function apply(client:any,next:any){
   if(!active)return;const user=next?.user||null;setAccountUser(user);if(!user)return;
   try{
    const hasLocal=Boolean(localStorage.getItem(storageKey));
    if(!hasLocal){const record=await loadAccountVoxel(client,user,sessionId);const payload=record?.payload as any;if(active&&payload?.asset?.dataUrl){setAsset(payload.asset as Asset);setMesh((payload.mesh||emptyMesh()) as Mesh);if(payload.mint?.tokenId)setMinted(payload.mint as Mint);if(payload.idea)setBrief(v=>({...v,idea:String(payload.idea)}));if(Number.isFinite(payload.generationsLeft))setGenerationsLeft(Number(payload.generationsLeft));setStatus('done');setMessage(payload.mint?.tokenId?`VoxelFlip #${payload.mint.tokenId} restored from your Google account.`:'Your paid voxel was restored from your Google account.')}}
    if(active)setAccountMessage('Google account connected · My Voxels sync is on.');
   }catch(e){if(active)setAccountMessage(e instanceof Error?e.message:'Google account connected, but this voxel could not be restored.');}
  }
  getSupabaseBrowserAsync().then(async client=>{if(!active)return;accountClient.current=client;const {data}=await client.auth.getSession();await apply(client,data.session);const auth=client.auth.onAuthStateChange((_event:any,next:any)=>apply(client,next));subscription=auth.data.subscription}).catch(()=>{});
  return()=>{active=false;subscription?.unsubscribe?.()};
 },[sessionId,storageKey]);
 useEffect(()=>{
  if(!accountUser||!asset)return;
  const payload={asset,mesh,mint:minted||undefined,generationsLeft,idea:brief.idea,updatedAt:new Date().toISOString()};
  const timer=setTimeout(()=>{getSupabaseBrowserAsync().then(client=>{accountClient.current=client;return saveVoxelToAccount(client,accountUser,sessionId,payload)}).then(()=>mounted.current&&setAccountMessage('Saved to My Voxels on your Google account.')).catch(e=>mounted.current&&setAccountMessage(e instanceof Error?e.message:'Could not sync this voxel to your account.'));},500);
  return()=>clearTimeout(timer);
 },[accountUser?.id,sessionId,asset?.name,asset?.dataUrl,mesh.status,mesh.taskId,mesh.modelUrl,minted?.tokenId,minted?.hash,minted?.openSeaUrl,generationsLeft,brief.idea]);
 async function chooseReference(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;try{setMessage('');setBrief(v=>({...v,referenceName:file.name,reference:''}));const data=await compressReference(file);setBrief(v=>({...v,reference:data,referenceName:file.name}));}catch(err){setMessage(err instanceof Error?err.message:'Could not read that image.')}}
 async function generate(improve=false){if(!sessionId){setStatus('error');setMessage('Checkout session missing. Return to VoxelPop and purchase the asset again.');return}if(brief.idea.trim().length<8){setStatus('error');setMessage('Add a short description of what you want.');return}if(improve&&!asset)return;setStatus('generating');setMessage(improve?'Improving your voxel while keeping the same design…':'Creating your paid voxel image…');try{const response=await fetch('/api/creator-pack/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId,idea:brief.idea.trim(),style:brief.style,reference:improve?asset?.dataUrl:brief.reference,improve})});const data=await response.json();if(!response.ok||!Array.isArray(data.images)||data.images.length!==1)throw new Error(data.error||'Generation failed.');const nextAsset={name:data.names?.[0]||'your-voxel',dataUrl:data.images[0]};setAsset(nextAsset);setMesh(emptyMesh());setMinted(null);setGenerationsLeft(Math.max(0,Number(data.generationsLeft||0)));setStatus('done');setMessage(improve?'Improved voxel ready. Like this one? Build its 3D mesh below.':'Your voxel is ready. You can improve it or build the 3D mesh.');}catch(err){setStatus(asset?'done':'error');setMessage(err instanceof Error?err.message:'Generation failed.')}}
 async function pollMesh(taskId:string){for(let i=0;i<180;i++){if(!mounted.current)return;const q=new URLSearchParams({sessionId,taskId});const response=await fetch(`/api/creator-pack/mesh?${q}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not read mesh status.');const s=String(data.status||'').toUpperCase();if(s==='SUCCEEDED'&&data.modelUrl){setMesh(v=>({...v,status:'ready',progress:100,modelUrl:data.modelUrl,error:''}));return}if(['FAILED','EXPIRED','CANCELED','CANCELLED'].includes(s))throw new Error(data.error||'The 3D provider could not complete this mesh.');setMesh(v=>({...v,status:'building',progress:Math.max(1,Math.min(99,Number(data.progress||0)))}));await wait(4000)}throw new Error('The mesh is taking longer than expected. Retry the status check shortly.');}
 async function buildMesh(){if(!asset)return;setMesh({...emptyMesh(),status:'starting',progress:1});try{const meshImage=await prepareMeshImage(asset.dataUrl);const response=await fetch('/api/creator-pack/mesh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId,index:0,image:meshImage,name:asset.name,idea:brief.idea,forceRestart:mesh.status==='error'})});const data=await response.json();if(!response.ok||!data.taskId)throw new Error(data.error||'Could not start the 3D mesh.');setMesh(v=>({...v,status:'building',progress:2,taskId:data.taskId}));await pollMesh(data.taskId);}catch(err){setMesh(v=>({...v,status:'error',error:err instanceof Error?err.message:'3D mesh generation failed.'}))}}
 async function shareVoxel(){const shareUrl='https://www.voxelvault.io/?utm_source=customer_share&utm_medium=referral&utm_campaign=voxelpop_share&utm_content=finished_asset';const shareData={title:'VoxelPop',text:'I made a 3D voxel with VoxelPop. Try making yours for $1.99.',url:shareUrl};try{if(navigator.share){await navigator.share(shareData);setMessage('Shared. Thanks for showing off your VoxelPop.');return}if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(shareUrl);setMessage('VoxelPop share link copied.');return}window.prompt('Copy this link to share VoxelPop:',shareUrl)}catch(err){if(err instanceof DOMException&&err.name==='AbortError')return;try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(shareUrl);setMessage('VoxelPop share link copied.');return}}catch{}window.prompt('Copy this link to share VoxelPop:',shareUrl)}}
 function openForge(){
  if(!asset||mesh.status!=='ready')return;
  const payload={asset,mesh,mint:minted||undefined,generationsLeft,idea:brief.idea,updatedAt:new Date().toISOString()};
  try{localStorage.setItem(storageKey,JSON.stringify(payload))}catch{}
  if(accountUser){getSupabaseBrowserAsync().then(client=>saveVoxelToAccount(client,accountUser,sessionId,payload)).catch(()=>{})}
  window.location.href=`/forge/real?focus_session=${encodeURIComponent(sessionId)}`;
 }
 const downloadQuery=mesh.taskId?new URLSearchParams({sessionId,taskId:mesh.taskId,download:'1'}).toString():'';const previewQuery=mesh.taskId?new URLSearchParams({sessionId,taskId:mesh.taskId,preview:'1'}).toString():'';const previewUrl=previewQuery?`/api/creator-pack/mesh?${previewQuery}`:'';
 return <main className={styles.page}><nav className={styles.nav}><a href="/"><img src="/voxelpop/voxelpop-logo.png" alt="VoxelPop" style={{width:44,height:44,borderRadius:12}}/><b>VoxelPop</b></a><em>PAYMENT COMPLETE</em></nav><section className={styles.shell}>
  <div className={styles.header}><p>YOUR VOXELPOP ASSET</p><h1>{status==='done'?'Make it move.':'Now make it yours.'}</h1><span>{status==='done'?'Choose the version you love, then turn it into a real 3D mesh.':'Confirm the direction below. Your $1.99 purchase creates one custom voxel asset.'}</span>{accountMessage&&<small style={{display:'block',marginTop:10}}>{accountMessage}</small>}</div>
  {status!=='done'&&<div className={styles.builder}><label><b>Describe the person, character, product, pet or object</b><textarea maxLength={600} value={brief.idea} onChange={e=>setBrief(v=>({...v,idea:e.target.value}))}/></label><div className={styles.styles}><b>Finish</b><div>{[['polished','Polished'],['chunky','Chunky'],['cute','Cute'],['dark','Dark fantasy']].map(([value,label])=><button type="button" key={value} className={brief.style===value?styles.active:''} onClick={()=>setBrief(v=>({...v,style:value}))}>{label}</button>)}</div></div><label className={styles.upload}><input type="file" accept="image/png,image/jpeg,image/webp" onChange={chooseReference}/>{brief.reference?<img src={brief.reference} alt="Reference preview"/>:<span>＋</span>}<div><b>{brief.referenceName||'Optional reference image'}</b><small>{brief.reference?'Reference will guide your voxel':'Add a photo, sketch, product, pet or character'}</small></div></label><button className={styles.generate} disabled={status==='generating'} onClick={()=>generate(false)}>{status==='generating'?'Generating your voxel…':'Generate my voxel'}</button><small className={styles.note}>Your purchase includes the original plus up to 2 improvement passes.</small></div>}
  {message&&<div className={`${styles.message} ${status==='error'?styles.messageError:''}`}>{status==='generating'&&<i/>}{message}</div>}
  {status==='done'&&asset&&<><div className={styles.assetHeader}><div><p>GENERATE → IMPROVE → MESH → MOVE</p><h2>Your voxel</h2></div><span>{minted?.tokenId?`Already minted as VoxelFlip #${minted.tokenId}. Open it anytime below.`:'Improve it before meshing, or build it now if you love this version.'}</span></div><div className={styles.meshGrid}><article className={styles.meshCard}><div className={styles.meshCardTop}><b>01</b><span>{asset.name.replaceAll('-',' ')}</span></div>{mesh.status==='ready'&&previewUrl?<GeneratedMeshViewer url={previewUrl} label={asset.name}/>:<div className={styles.sourceImage}><img src={asset.dataUrl} alt="Your generated voxel"/>{['starting','building'].includes(mesh.status)&&<div className={styles.meshProgress}><i style={{width:`${Math.max(4,mesh.progress)}%`}}/><b>{mesh.status==='starting'?'Starting 3D build':`Building mesh · ${mesh.progress}%`}</b></div>}</div>}<div className={styles.meshActions}>{mesh.status==='idle'&&<>{generationsLeft>0&&<button className={styles.improveButton} onClick={()=>generate(true)}>✨ Improve this voxel · {generationsLeft} {generationsLeft===1?'try':'tries'} left</button>}<button onClick={buildMesh}>Build this version in 3D</button>{generationsLeft>0&&<small className={styles.improveNote}>Improvement keeps the same idea but cleans up voxel geometry and makes it more 3D-ready.</small>}</>}{['starting','building'].includes(mesh.status)&&<button disabled>Building 3D Mesh…</button>}{mesh.status==='error'&&<><p>{mesh.error}</p><button onClick={buildMesh}>Retry 3D Mesh</button></>}{mesh.status==='ready'&&<><button onClick={openForge}>Add this 3D voxel to Forge →</button><small className={styles.improveNote}>This carries this exact finished voxel into Forge in the same browser. It does not mint or spend ETH.</small>{minted?.tokenId?<><a href={`/voxelflip/mint?session_id=${encodeURIComponent(sessionId)}`}>Open minted 3D · VoxelFlip #{minted.tokenId} →</a><small className={styles.improveNote}>✓ Already minted on Base. Opening it will not mint again.</small>{minted.openSeaUrl&&<a className={styles.secondaryDownload} href={minted.openSeaUrl} target="_blank" rel="noreferrer">Open minted NFT on OpenSea</a>}</>:<a href={`/voxelflip/mint?session_id=${encodeURIComponent(sessionId)}`}>Mint as VoxelFlip →</a>}<a className={styles.secondaryDownload} href={`/api/creator-pack/mesh?${downloadQuery}`}>Download GLB</a><a className={styles.secondaryDownload} href={asset.dataUrl} download={`${asset.name}.png`}>Download image</a><button className={styles.secondaryDownload} onClick={shareVoxel}>Share my VoxelPop</button></>}</div></article></div></>}
  <footer><a href="/studio#my-voxels">← Back to My Voxels</a><span>AI-generated output can vary. Inspect your asset before production use.</span></footer></section></main>;
}
