import { acquisitionPolicy, rankPropertyCandidates } from '../real-estate/acquisition-engine.js';

export const SPATIAL_ACQUISITION_DEMO_CANDIDATES = Object.freeze([
  {
    id: 'CANDIDATE-001',
    label: 'Low-cost single-family demo',
    location: 'Example Midwest market',
    purchasePrice: 22500,
    closingCosts: 1700,
    immediateRepairs: 6200,
    backTaxes: 0,
    initialReserve: 2500,
    monthlyRent: 725,
    annualPropertyTax: 1150,
    annualInsurance: 1200,
    monthlyHoa: 0,
    monthlyUtilities: 0,
    managementRate: 0.09,
    vacancyRate: 0.08,
    maintenanceRate: 0.1,
    titleVerified: true,
    liensCleared: true,
    taxesCurrent: true,
    habitable: true,
    rentalLegal: true,
    insuranceAvailable: true,
    inspectionComplete: true,
    marketRentVerified: true,
    propertyManagerConfirmed: true,
    floodRiskReviewed: true,
    utilityArrearsReviewed: true,
  },
  {
    id: 'CANDIDATE-002',
    label: 'Ultra-cheap house demo',
    location: 'Example distressed market',
    purchasePrice: 4900,
    closingCosts: 1300,
    immediateRepairs: 18500,
    backTaxes: 3400,
    initialReserve: 3000,
    monthlyRent: 650,
    annualPropertyTax: 900,
    annualInsurance: 1450,
    managementRate: 0.1,
    vacancyRate: 0.12,
    maintenanceRate: 0.12,
    titleVerified: false,
    liensCleared: false,
    taxesCurrent: false,
    habitable: false,
    rentalLegal: true,
    insuranceAvailable: false,
    inspectionComplete: false,
    marketRentVerified: false,
    propertyManagerConfirmed: false,
    floodRiskReviewed: false,
    utilityArrearsReviewed: false,
  },
  {
    id: 'CANDIDATE-003',
    label: 'Small duplex demo',
    location: 'Example secondary city',
    purchasePrice: 48500,
    closingCosts: 2600,
    immediateRepairs: 7500,
    backTaxes: 0,
    initialReserve: 4500,
    monthlyRent: 1350,
    annualPropertyTax: 2300,
    annualInsurance: 1850,
    monthlyUtilities: 90,
    managementRate: 0.09,
    vacancyRate: 0.08,
    maintenanceRate: 0.1,
    titleVerified: true,
    liensCleared: true,
    taxesCurrent: true,
    habitable: true,
    rentalLegal: true,
    insuranceAvailable: true,
    inspectionComplete: false,
    marketRentVerified: true,
    propertyManagerConfirmed: true,
    floodRiskReviewed: true,
    utilityArrearsReviewed: true,
  },
]);

export function buildAcquisitionResearchManifest(candidates = SPATIAL_ACQUISITION_DEMO_CANDIDATES) {
  return rankPropertyCandidates(Array.isArray(candidates) ? candidates : []).map((candidate, index) => ({
    id: candidate.id || `candidate-${index + 1}`,
    rank: index + 1,
    kind: 'property-research-candidate',
    title: candidate.label,
    location: candidate.location,
    score: candidate.score,
    status: candidate.status,
    eligibleForHumanReview: candidate.eligibleForHumanReview === true,
    executionAllowed: false,
    truthLabel: candidate.status === 'reject'
      ? 'DEMO RESEARCH · HARD STOP'
      : candidate.status === 'review-ready'
        ? 'DEMO RESEARCH · HUMAN REVIEW ELIGIBLE'
        : 'DEMO RESEARCH · DILIGENCE OPEN',
    economics: {
      purchasePrice: candidate.economics.purchasePrice,
      totalBasis: candidate.economics.totalBasis,
      monthlyRent: candidate.economics.monthlyRent,
      monthlyOperatingExpenses: candidate.economics.monthlyOperatingExpenses,
      monthlyNet: candidate.economics.monthlyNet,
      modeledNetYield: candidate.economics.modeledNetYield,
    },
    failedHardGates: [...candidate.failedHardGates],
    warnings: [...candidate.warnings],
    note: 'Simulation/research candidate only. Ranking is not an authorization to purchase, a listing offer, or an investment recommendation.',
  }));
}

export function summarizeAcquisitionResearch(entries = []) {
  const list = Array.isArray(entries) ? entries : [];
  return {
    total: list.length,
    reviewEligible: list.filter((item) => item.eligibleForHumanReview).length,
    rejected: list.filter((item) => item.status === 'reject').length,
    diligenceOpen: list.filter((item) => item.status === 'diligence').length,
    executable: list.filter((item) => item.executionAllowed === true).length,
    livePropertyExecutionReady: acquisitionPolicy.livePropertyExecutionReady === true,
  };
}
