-- First-party conversion tracking for the VoxelPop $1.99 funnel.
-- No prompt text, email address, IP address, or other direct identifier is stored.

create table if not exists public.voxelpop_conversion_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in (
    'studio_view',
    'prompt_started',
    'checkout_clicked',
    'checkout_started',
    'checkout_cancelled',
    'purchase_completed',
    'image_generation_started',
    'image_generated',
    'image_generation_failed',
    'mesh_started',
    'mesh_completed',
    'mesh_failed',
    'glb_downloaded'
  )),
  event_key text not null unique,
  flow_id uuid,
  stripe_session_id text,
  stripe_event_id text,
  source text,
  medium text,
  campaign text,
  content text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists voxelpop_conversion_events_created_idx
  on public.voxelpop_conversion_events(created_at desc);
create index if not exists voxelpop_conversion_events_event_idx
  on public.voxelpop_conversion_events(event_name, created_at desc);
create index if not exists voxelpop_conversion_events_flow_idx
  on public.voxelpop_conversion_events(flow_id)
  where flow_id is not null;
create index if not exists voxelpop_conversion_events_session_idx
  on public.voxelpop_conversion_events(stripe_session_id)
  where stripe_session_id is not null;

alter table public.voxelpop_conversion_events enable row level security;
revoke all on table public.voxelpop_conversion_events from anon, authenticated;
grant select, insert, update on table public.voxelpop_conversion_events to service_role;
grant usage, select on sequence public.voxelpop_conversion_events_id_seq to service_role;

create or replace function public.voxelpop_funnel_summary(since_at timestamptz)
returns table(event_name text, event_count bigint)
language sql
security definer
set search_path = public
as $$
  select e.event_name, count(*)::bigint as event_count
  from public.voxelpop_conversion_events e
  where e.created_at >= since_at
  group by e.event_name
  order by e.event_name;
$$;

revoke all on function public.voxelpop_funnel_summary(timestamptz) from public, anon, authenticated;
grant execute on function public.voxelpop_funnel_summary(timestamptz) to service_role;

comment on table public.voxelpop_conversion_events is
  'Privacy-minimized first-party VoxelPop conversion funnel events.';
