-- VoxelFlip Factory accounting ledger.
-- Service-role only: browser users must never be able to fabricate profit or costs.

create table if not exists public.voxelflip_profit_ledger (
  id bigint generated by default as identity primary key,
  wallet text not null check (wallet ~* '^0x[0-9a-f]{40}$'),
  contract_address text check (contract_address is null or contract_address ~* '^0x[0-9a-f]{40}$'),
  token_id text,
  session_id text,
  entry_type text not null check (entry_type in (
    'sale_gross',
    'sale_fee',
    'royalty_income',
    'mint_gas',
    'listing_gas',
    'generation_cost',
    'mesh_cost',
    'other_cost',
    'adjustment'
  )),
  direction text not null check (direction in ('income','cost')),
  amount_eth numeric(38,18),
  amount_usd_cents bigint,
  source text not null,
  source_ref text not null unique,
  tx_hash text check (tx_hash is null or tx_hash ~* '^0x[0-9a-f]{64}$'),
  settlement_status text not null default 'pending' check (settlement_status in ('pending','estimated','verified')),
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (amount_eth is not null or amount_usd_cents is not null),
  check (amount_eth is null or amount_eth >= 0),
  check (amount_usd_cents is null or amount_usd_cents >= 0)
);

create index if not exists voxelflip_profit_ledger_wallet_time_idx
  on public.voxelflip_profit_ledger (lower(wallet), occurred_at desc);
create index if not exists voxelflip_profit_ledger_token_idx
  on public.voxelflip_profit_ledger (lower(contract_address), token_id);
create index if not exists voxelflip_profit_ledger_type_idx
  on public.voxelflip_profit_ledger (entry_type, settlement_status);

alter table public.voxelflip_profit_ledger enable row level security;
revoke all on table public.voxelflip_profit_ledger from anon, authenticated;
grant select, insert, update on table public.voxelflip_profit_ledger to service_role;
grant usage, select on sequence public.voxelflip_profit_ledger_id_seq to service_role;

comment on table public.voxelflip_profit_ledger is
  'Server-owned VoxelFlip income/cost ledger. A sale is gross proceeds until complete verified cost coverage exists; minting and unsold inventory never count as profit.';
