create table if not exists public.voxelflip_neural_memory (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('market_snapshot','recommendation','admin_config','trade_note')),
  wallet text,
  contract_address text,
  token_id text,
  confidence text,
  payload jsonb not null default '{}'::jsonb,
  observed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists voxelflip_neural_memory_wallet_time_idx
  on public.voxelflip_neural_memory (wallet, observed_at desc);

create index if not exists voxelflip_neural_memory_kind_time_idx
  on public.voxelflip_neural_memory (kind, observed_at desc);

alter table public.voxelflip_neural_memory enable row level security;

revoke all on table public.voxelflip_neural_memory from anon, authenticated;
grant select, insert, update, delete on table public.voxelflip_neural_memory to service_role;
grant usage, select on sequence public.voxelflip_neural_memory_id_seq to service_role;

comment on table public.voxelflip_neural_memory is
  'Server-only VoxelFlip Neural Core memory. Browser roles have no direct access; all reads and writes pass through authenticated admin routes.';
