import { NextResponse } from 'next/server';
import { licensePrice } from '../../../../lib/x402';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function GET(request: Request) {
  const origin = new URL(request.url).origin;

  return NextResponse.json({
    openapi: '3.1.0',
    info: {
      title: 'Galactic x402 Machine Licensing API',
      version: '1.0.0',
      description: 'Free discovery plus x402-paid one-use machine license receipts for eligible Base VoxelFlip NFTs.'
    },
    servers: [{ url: origin }],
    paths: {
      '/api/paylink': {
        get: {
          summary: 'Read direct Base USDC payment details.',
          responses: { '200': { description: 'Paylink details.' } }
        }
      },
      '/api/agent/health': {
        get: {
          summary: 'Read x402 and licensing status.',
          responses: { '200': { description: 'Service health.' } }
        }
      },
      '/api/agent/manifest': {
        get: {
          summary: 'Machine-readable service manifest.',
          responses: { '200': { description: 'Service manifest.' } }
        }
      },
      '/api/licenses/catalog': {
        get: {
          summary: 'Free catalog of licensable assets.',
          parameters: [
            { name: 'limit', in: 'query', required: false, schema: { type: 'integer', minimum: 1, maximum: 80, default: 24 } }
          ],
          responses: {
            '200': { description: 'Current catalog.' },
            '503': { description: 'Base RPC unavailable.' }
          }
        }
      },
      '/api/licenses/use': {
        post: {
          summary: `Buy one machine-use license for ${licensePrice()} USDC through x402.`,
          description: 'Returns HTTP 402 when no valid x402 payment is supplied. After a successful payment and a successful asset eligibility check, returns one non-transferable machine-use license receipt.',
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  required: ['tokenId'],
                  properties: {
                    tokenId: { type: 'string', pattern: '^\\d+$', examples: ['1'] },
                    clientId: { type: 'string', maxLength: 120, examples: ['my-agent'] },
                    useCase: { type: 'string', maxLength: 240, examples: ['render this voxel in one generated scene'] }
                  }
                }
              }
            }
          },
          responses: {
            '200': { description: 'Paid license receipt.' },
            '400': { description: 'Invalid request.' },
            '402': { description: 'x402 payment required.' },
            '404': { description: 'Token not eligible.' },
            '503': { description: 'Payment facilitator or Base RPC unavailable.' }
          }
        }
      }
    },
    components: {
      securitySchemes: {
        x402: {
          type: 'apiKey',
          in: 'header',
          name: 'PAYMENT-SIGNATURE',
          description: 'Base64-encoded x402 payment payload generated by an x402-compatible client from the HTTP 402 response.'
        }
      }
    }
  }, {
    headers: { 'Cache-Control': 'public, max-age=60, s-maxage=60' }
  });
}
